apiVersion: v1
kind: Namespace
metadata:
  name: flux-ui
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  annotations:
    metadata.weave.works/description: This is the source location for the Weave GitOps
      Dashboard's helm chart.
  labels:
    app.kubernetes.io/component: ui
    app.kubernetes.io/created-by: weave-gitops-cli
    app.kubernetes.io/name: weave-gitops-dashboard
    app.kubernetes.io/part-of: weave-gitops
  name: flux-ui
  namespace: flux-ui
spec:
  interval: 1h0m0s
  type: oci
  url: oci://ghcr.io/weaveworks/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  annotations:
    metadata.weave.works/description: This is the Weave GitOps Dashboard.  It provides
      a simple way to get insights into your GitOps workloads.
  name: flux-ui
  namespace: flux-ui
spec:
  chart:
    spec:
      chart: weave-gitops
      sourceRef:
        kind: HelmRepository
        name: flux-ui
        namespace: flux-ui
  interval: 1h0m0s
  values:
    adminUser:
      create: true
      passwordHash: $2a$10$HkavWyTYO.ytMAqhMLDf5.W8BfvhWAV0ny6Qk100DpxglPqMXIJ8S
      username: admin
    ingress:
      enabled: true
      className: "kong"
      annotations: {}
      hosts:
        - paths:
            - path: /flux-ui
              pathType: ImplementationSpecific
      tls: []
